apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: swiss-openapi-kundenbeziehung
  labels:
    app: swiss-openapi-api
    component: secrets
type: Opaque
data:
  # JWT Secret (base64 encoded) - CHANGE IN PRODUCTION
  JWT_SECRET: Y2hhbmdlLXRoaXMtand0LXNlY3JldC1pbi1wcm9kdWN0aW9uLXRvLWEtc3Ryb25nLXJhbmRvbS1rZXk=
  
  # MongoDB Connection
  MONGODB_USERNAME: YXBpLXNlcnZpY2U=  # api-service
  MONGODB_PASSWORD: Y2hhbmdlLXRoaXMtbW9uZ29kYi1wYXNzd29yZC1pbi1wcm9kdWN0aW9u  # change-this-mongodb-password-in-production
  
  # Redis Password (if Redis AUTH is enabled)
  REDIS_PASSWORD: Y2hhbmdlLXRoaXMtcmVkaXMtcGFzc3dvcmQtaW4tcHJvZHVjdGlvbg==  # change-this-redis-password-in-production

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: swiss-openapi-kundenbeziehung
  labels:
    app: mongodb
    component: secrets
type: Opaque
data:
  # MongoDB Root User (base64 encoded) - CHANGE IN PRODUCTION
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==  # root
  MONGO_INITDB_ROOT_PASSWORD: Y2hhbmdlLXRoaXMtcm9vdC1wYXNzd29yZC1pbi1wcm9kdWN0aW9u  # change-this-root-password-in-production
  
  # MongoDB Application Database
  MONGO_INITDB_DATABASE: b3BlbmFwaS1rdW5kZW5iZXppZWh1bmc=  # openapi-kundenbeziehung
  MONGO_API_PASSWORD: Y2hhbmdlLXRoaXMtbW9uZ29kYi1wYXNzd29yZC1pbi1wcm9kdWN0aW9u  # change-this-mongodb-password-in-production

---
# TLS Certificate Secret - Replace with your actual certificates
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: swiss-openapi-kundenbeziehung
  labels:
    app: nginx
    component: tls
type: kubernetes.io/tls
data:
  # Server certificate for api.kundenbeziehung.ch
  # Replace with your actual certificate in base64 format
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  
  # Server private key
  # Replace with your actual private key in base64 format  
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

---
# CA Certificate Secret for mTLS client verification
apiVersion: v1
kind: Secret
metadata:
  name: ca-certificates
  namespace: swiss-openapi-kundenbeziehung
  labels:
    app: nginx
    component: ca
type: Opaque
data:
  # Certificate Authority certificate for client verification
  # Replace with your actual CA certificate in base64 format
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=

---
# Docker Registry Secret (if using private registry)
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: swiss-openapi-kundenbeziehung
type: kubernetes.io/dockerconfigjson
data:
  # Replace with your actual docker registry credentials
  .dockerconfigjson: |
    eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==